### ISSUE TITLE
Support Bang Finder Methods

### ISSUE THREAD

**Issue by nateklaiber** [quicksprout/naas-api-client-ruby#1]
### Tasks

* [x] Add `retrieve!` finder method for `Project`
* [ ] Add `retrieve!` finder method for `Campaign`
* [ ] Add `retrieve!` finder method for `CampaignEmailTemplate`
* [ ] Add `retrieve!` finder method for `Subscriber`
* [ ] Add `retrieve!` finder method for `SubscriberEmailAddress`
* [ ] Add `retrieve!` finder method for `AccountSmtpSetting`

### Notes

This will raise exceptions if the record is not found.
